import PDFDocument from "pdfkit";

export function generatePDF(transactions, res) {
  try {
    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=Expense_Report.pdf"
    );

    doc.pipe(res);

    // --- Header ---
    doc
      .fontSize(20)
      .fillColor("#4f46e5")
      .text("Expense Tracker", { align: "left" });

    doc
      .fontSize(10)
      .fillColor("#6b7280")
      .text("Financial Transaction Report", { align: "left" });

    const reportDate = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    doc.text(`Generated on: ${reportDate}`, { align: "left" });
    doc.moveDown(2);

    // --- Summary Section ---
    let totalIncome = 0;
    let totalExpense = 0;
    transactions.forEach((t) => {
      if (t.type === "income") totalIncome += t.amount;
      else totalExpense += t.amount;
    });
    const balance = totalIncome - totalExpense;

    const summaryY = doc.y;
    drawCard(doc, "Total Income", `+${totalIncome}`, "#10b981", 50, summaryY);
    drawCard(
      doc,
      "Total Expense",
      `-${totalExpense}`,
      "#ef4444",
      200,
      summaryY
    );
    drawCard(doc, "Net Balance", `${balance}`, "#3b82f6", 350, summaryY);

    doc.moveDown(4);

    // --- Transactions Table ---
    const tableTop = 250;
    const itemMargin = 10;

    // Table Headers
    doc.font("Helvetica-Bold");
    generateTableRow(
      doc,
      tableTop,
      "Date",
      "Category",
      "Type",
      "Pay Method",
      "Amount"
    );
    generateHr(doc, tableTop + 20);
    doc.font("Helvetica");

    // Table Rows
    let y = tableTop + 30;
    let i = 0;

    transactions.forEach((t) => {
      // Check for page break
      if (y > doc.page.height - 50) {
        doc.addPage();
        y = 50; // Reset to top
        // Optional: Redraw headers here if desired
      }

      // Alternating row background
      if (i % 2 === 0) {
        doc
          .rect(50, y - 5, 500, 25)
          .fillColor("#f9fafb")
          .fill();
      }

      doc.fillColor("#1f2937");
      generateTableRow(
        doc,
        y,
        new Date(t.date).toLocaleDateString(),
        t.category,
        t.type.toUpperCase(),
        t.paymentMethod,
        t.type === "income" ? `+${t.amount}` : `-${t.amount}`
      );

      generateHr(doc, y + 20);

      y += 30; // Move down for next row
      i++;
    });

    // Footer
    doc
      .fontSize(10)
      .fillColor("#9ca3af")
      .text(
        "End of Report. Generated by Expense Tracker.",
        50,
        doc.page.height - 50,
        { align: "center", width: 500 }
      );

    doc.end();
  } catch (error) {
    console.error("PDF Export Error:", error);
    // Don't throw after headers sent, just log
  }
}

function drawCard(doc, title, value, color, x, y) {
  doc
    .rect(x, y, 130, 60)
    .fillColor("#f3f4f6")
    .fill()
    .strokeColor("#e5e7eb")
    .stroke();

  doc
    .fillColor("#374151")
    .fontSize(10)
    .text(title, x + 10, y + 10);
  doc
    .fillColor(color)
    .fontSize(16)
    .font("Helvetica-Bold")
    .text(value, x + 10, y + 30);
  doc.font("Helvetica");
}

function generateTableRow(doc, y, date, category, type, payment, amount) {
  doc
    .fontSize(10)
    .text(date, 50, y)
    .text(category, 150, y)
    .text(type, 280, y)
    .text(payment, 350, y, { width: 90, align: "left" })
    .text(amount, 440, y, { align: "right" }); // Right align amount
}

function generateHr(doc, y) {
  doc.strokeColor("#e5e7eb").lineWidth(1).moveTo(50, y).lineTo(550, y).stroke();
}
